[DNM] updated references of base plugins to netcommon
ansible-collections/cisco.asa pull request #150
Opened 2022-02-04 06:07 UTC by KB-perByte

##### SUMMARY

Minimum required ansible.netcommon version is 2.5.0
Updated base plugin references to ansible.netcommon
Depends-on: https://github.com/ansible-collections/ansible.netcommon/pull/358

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2022-04-21 13:42 UTC, Qalthos requested changes

2022-04-21 13:42 UTC, Qalthos commented on changelogs/fragments/netcommon_ref_update.yaml
> +  - "Minimum required ansible.netcommon version is 2.5.0."
```suggestion
  - "Minimum required ansible.netcommon version is 2.5.1."
```

2022-04-21 13:42 UTC, Qalthos commented on galaxy.yml
> +  "ansible.netcommon": ">=2.5.0"
This has to be 2.5.1 to work
```suggestion
  "ansible.netcommon": ">=2.5.1"
```

2022-04-25 13:20 UTC, Qalthos approved these changes

2022-05-04 12:22 UTC, justjais commented
recheck

2022-05-04 16:53 UTC, goneri commented
recheck

2022-05-09 06:08 UTC, justjais commented
Changes were merged via https://github.com/ansible-collections/cisco.asa/pull/160. Closing the PR

2022-05-09 06:08 UTC, closed without merging