Add GH workdlow actions for Unit and Sanity tests
ansible-collections/cisco.asa pull request #169
Opened 2022-05-23 14:07 UTC by justjais

Signed-off-by: Sumit Jaiswal <sjaiswal@redhat.com>

##### SUMMARY

Add GH workdlow actions for Unit and Sanity tests

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

asa

##### ADDITIONAL INFORMATION

```paste below

```

2022-05-24 10:35 UTC, justjais commented
recheck

2022-08-24 05:35 UTC, justjais commented
recheck

2022-10-12 06:51 UTC, KB-perByte requested changes

2022-10-12 06:51 UTC, KB-perByte commented on .pre-commit-config.yaml
>          args: [-l, "79"]
```suggestion
        args: [-l, "100"]
```

2022-10-12 06:51 UTC, KB-perByte commented on pyproject.toml
> +line-length = 79
```suggestion
line-length = 100
```

2022-10-12 06:51 UTC, KB-perByte commented on .github/workflows/test.yml
> +  changelog:
we might consider adding ansible-lint

2022-10-12 06:51 UTC, KB-perByte commented on .pre-commit-config.yaml
> +    rev: v4.2.0
```suggestion
    rev: v4.3.0
```

2022-10-12 06:51 UTC, KB-perByte commented on .pre-commit-config.yaml
> +    rev: 22.3.0
```suggestion
    rev: 22.6.0
```

2022-10-12 06:53 UTC, KB-perByte commented on .pre-commit-config.yaml
>  ---
we might also add/enable isort and add-tailing-comma to the pre-commit CI
ref : https://github.com/ansible-collections/cisco.ios/blob/main/.pre-commit-config.yaml

2022-10-12 09:42 UTC, KB-perByte approved these changes

2022-10-12 14:16 UTC, merged