[WIP DNM]To add asa feature of supporting any4/any6 for asa_acls source and destination
ansible-collections/cisco.asa pull request #64
Opened 2020-07-31 08:12 UTC by justjais

##### SUMMARY

[WIP DNM]To add asa feature of supporting any4/any6 for asa_acls source and destination

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

ios_acls

##### ADDITIONAL INFORMATION

```paste below

```

2020-11-23 06:09 UTC, justjais commented
recheck

2020-11-24 11:17 UTC, justjais commented
recheck

2020-11-24 13:23 UTC, GomathiselviS commented
recheck

2020-11-25 13:06 UTC, rohitthakur2590 commented on plugins/modules/asa_acls.py
> +# access-list global_access line 3 remark test global access
The examples below needed to be updated with config as dict.

2020-11-25 13:09 UTC, rohitthakur2590 requested changes

2020-11-25 13:09 UTC, rohitthakur2590 commented on plugins/modules/asa_acls.py
> +# access-list R1_traffic line 1 remark test_v6_acl
Examples here needs to be updated with config as dict.

2020-11-26 04:50 UTC, rohitthakur2590 approved these changes

2020-11-26 09:34 UTC, merged